package smart.Controller;

import javassist.NotFoundException;
import org.hibernate.TransactionException;
import org.hibernate.exception.ConstraintViolationException;
import org.hibernate.internal.ExceptionMapperStandardImpl;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.http.ResponseEntity;
import org.springframework.security.core.userdetails.UserDetailsService;
import org.springframework.transaction.TransactionSystemException;
import org.springframework.web.bind.annotation.*;
import smart.DTO.PointDto;
import smart.DTO.UserDto;
import smart.Entities.Point;
import smart.Entities.User;
import smart.Exceptions.EmailExistsException;
import smart.Exceptions.UsernameExistsException;
import smart.Jwt.JwtAuthenticationResponse;
import smart.Jwt.JwtTokenUtil;
import smart.Jwt.JwtUser;
import smart.Jwt.JwtUserFactory;
import smart.Repositories.UserRepository;
import smart.Services.UserService;

import javax.servlet.http.HttpServletRequest;
import javax.validation.ConstraintViolation;
import javax.validation.Valid;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;

@RestController
@CrossOrigin(origins = "http://localhost:8100" )
public class UserController {

    @Value("${jwt.header}")
    private String tokenHeader;

    @Autowired
    private JwtTokenUtil jwtTokenUtil;

    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private UserRepository userRepository;

    @Autowired
    private UserService userService;


    @Autowired
    @Qualifier("jwtUserDetailsService")
    private UserDetailsService userDetailsService;

    @RequestMapping(value = "/user", method = RequestMethod.GET)
    public ResponseEntity<?> getAuthenticatedUser(HttpServletRequest request) {
        String token = request.getHeader(tokenHeader).substring(7);
        String username = jwtTokenUtil.getUsernameFromToken(token);
        JwtUser user = (JwtUser) userDetailsService.loadUserByUsername(username);
        return ResponseEntity.ok().body(user);
    }


    @RequestMapping(path="/user/all", method = RequestMethod.GET)
    public ResponseEntity<?> getAllUsers() throws ParseException {
        // This returns a JSON or XML with the users
        List<JwtUser> jwtUsers = new ArrayList<JwtUser>();
        for(User user: userService.getAllUsers()){
            jwtUsers.add(JwtUserFactory.create(user));
        }
        return ResponseEntity.ok().body(jwtUsers);
    }

    @RequestMapping(path="/user/add", method = RequestMethod.POST)
    public ResponseEntity<?> addUser(@RequestBody @Valid UserDto userDto, HttpServletRequest request) {
        try{
            User user = userService.addUser(userDto);
            JwtUserFactory.create(user);
            return ResponseEntity.ok().body(user);
        }catch (Exception e) {
            return ResponseEntity.status(400).body(e.getMessage());
        }
    }

    @RequestMapping(path="/user/location/set",method = RequestMethod.PUT)
    public ResponseEntity<?> setLocation(@RequestBody @Valid UserDto userDto, @RequestBody @Valid PointDto pointDto, HttpServletRequest reques){
        try{
            User user = userRepository.findByUsername(userDto.getUsername());
            Point location = new Point();
            location.setY(pointDto.getY());
            location.setX(pointDto.getX());
            userService.AddLocationToUser(user,location);
            return ResponseEntity.ok().body(user);
        }catch (NotFoundException nfe){
            return ResponseEntity.status(500).body(nfe.getMessage());
        }
    }
}
